# Generated by Django 2.1.15 on 2020-11-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendingmachine',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
