# Generated by Django 2.1.15 on 2020-11-15 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_beverageitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverageitem',
            name='vending_machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.VendingMachine'),
        ),
    ]
